### ISSUE TITLE
I cannot instantiate your class into an Object 

### ISSUE THREAD

**Issue by duaneandrea** [bssth/whatsapp-chatapi-sdk#1]
Im getting this error
{
  "data": "<br />\n<b>Fatal error</b>:  Uncaught Error: Class 'ChatApi' not found in /var/www/html/dhobo/index.php:3\nStack trace:\n#0 {main}\n  thrown in <b>/var/www/html/dhobo/index.php</b> on line <b>3</b><br />\n",
  "status": 200
}

When i test it in Chat Api Dashboard Webhook Simulate

**Comment by mikechip** [comment]
Hi!

Have you included chatapi.class.php? (or vendor/autoload.php if using composer)

**Comment by dan2378** [comment]
I have same problem how Duaneandrea this my code:
require_once "../vendor/autoload.php";

use Mike4ip;

$api = new ChatApi(
    '_token_', // Chat-Api.com token
    'https://foo.chat-api.com/instance1234' // Chat-Api.com API url
);

header('Content-Type: image/png');
readfile( $api->getQRCode() );


I receive this error:

Warning: The use statement with non-compound name 'Mike4ip' has no effect in E:\xampp3\htdocs\whatsapp-chatapi-sdk-master\test\testSDK.php on line 4

Fatal error: Uncaught Error: Class 'ChatApi' not found in E:\xampp3\htdocs\whatsapp-chatapi-sdk-master\test\testSDK.php:6 Stack trace: #0 {main} thrown in E:\xampp3\htdocs\whatsapp-chatapi-sdk-master\test\testSDK.php on line 6

line is $api = new ChatApi(

Thanks in advance

**Comment by mikechip** [comment]
> I have same problem how Duaneandrea this my code:

Just replace this:

`
use Mike4ip;
`

With this:

`
use Mike4ip\ChatApi;
`
