### ISSUE TITLE
login issue 

### ISSUE THREAD

**Issue by chiragpatel789** [bssth/whatsapp-chatapi-sdk#4]
hi ,

I  need Help For login Than After use  other api call,
I don't like scan every time for login .
it is possible  for api login Please Help me..?

Thanks...

**Comment by mikechip** [comment]
Hi. You need to login using QR code just once, then session will keep itself alive. Or you mean something else?

**Comment by chiragpatel789** [comment]
Hi.
ok i explain with example 
 i want send every day  some one invoce  so i make crone for that
cron will send invoice in his/her whatsapp so help me 
right now i use three day trial but when my mobile switch off than after  cron not work 
so  what i can do?
thanks

**Comment by mikechip** [comment]
chat-api.com needs your mobile phone to be online to work. It works like this because of WhatsApp limitations. If you need fully stand-alone bot, this library and service is not a good choice.

For example you can use this one: https://github.com/tgalal/yowsup,
