### ISSUE TITLE
$api->sendMessage() continuously sending same message. 

### ISSUE THREAD

**Issue by simongomes** [bssth/whatsapp-chatapi-sdk#6]
I have setup the webhook URL and used your php package to reply back whoever send a message to my mobile number using the $api->sendMessage() method. But it is sending reply multiple times and not stopping. What could be the issue?

**Comment by mikechip** [comment]
I apologize for noticing your question so late.

This usually means that Chat-Api sends updates several times in a row. Perhaps in the future the library will be better able to handle such situations.
